services:
  db:
    image: pgvector/pgvector:0.7.4-pg17
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - 5433:5432
  llm:
    image: ollama/ollama:0.3.12
    restart: unless-stopped
    volumes:
      - ./models:/root/.ollama/models
    ports:
      - 11435:11434
